post http://localhost:3001/api/notes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkVlbWVsaSIsImlkIjoiNmFiMjU1N2RmZTQ1MzdiYWQyYTkyOWNlIiwiaWF0IjoxNzkwMDczMjg1fQ.xP7QheD4nsnW6IOGw5lxi0YnK2c41U3XiHoFBVo03lg

{
    "content": "Single page apps use token based auth",
    "important": true
}